name: social_app
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2


  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  provider: ^4.0.4
  flutter_spinkit: "^4.1.2"
  flutter_svg: ^0.17.4
  cached_network_image: ^2.1.0+1
  get_it: ^4.0.1
  image_picker: ^0.6.5
  video_player: ^0.10.8+1
  path_provider: ^1.6.5
  uuid: ^2.0.4
  firebase_storage: ^3.1.5



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  fonts:
    - family: Signatra
      fonts:
        - asset: assets/fonts/Signatra.ttf
    - family: Bangers-Regular
      fonts:
        - asset: assets/fonts/Bangers-Regular.ttf 
  assets:
    - assets/images/

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
